CREATE TABLE IF NOT EXISTS FRIENDS(
  FRIEND_ID TEXT,
  NAME TEXT,
  MESSAGES_SHARED INTEGER,
  LINKS_SHARED INTEGER,
  NEW_ACCOUNTS_SHARED INTEGER,
  SUSPICIOUS_TIME_ACTIVITY INTEGER,
  MUTUAL_GROUPS INTEGER,
  RISK_SCORE REAL,
  PROBABILITY_HACKER REAL,
  RISK_LEVEL TEXT
);

INSERT INTO FRIENDS(FRIEND_ID, NAME, MESSAGES_SHARED, LINKS_SHARED, NEW_ACCOUNTS_SHARED, SUSPICIOUS_TIME_ACTIVITY, MUTUAL_GROUPS, RISK_SCORE, PROBABILITY_HACKER, RISK_LEVEL) VALUES
('F01','Amit',5,3,0,1,4,2.45,0.33,'SAFE'),
('F02','Priya',2,0,0,0,3,0.85,0.11,'SAFE'),
('F03','Rohan',15,9,2,6,7,6.25,0.84,'SUSPICIOUS'),
('F04','Sneha',1,0,0,0,1,0.25,0.03,'SAFE'),
('F05','Vikram',8,6,1,3,5,4.20,0.56,'SUSPICIOUS'),
('F06','Nisha',0,0,0,0,2,0.10,0.01,'SAFE'),
('F07','Kunal',20,15,5,10,8,7.45,1.00,'HIGH RISK'),
('F08','Meera',3,1,0,0,2,1.10,0.15,'SAFE');

SELECT FRIEND_ID, NAME, RISK_SCORE, PROBABILITY_HACKER, RISK_LEVEL
FROM FRIENDS;

SELECT *
FROM FRIENDS
WHERE RISK_LEVEL = 'HIGH RISK';

SELECT *
FROM FRIENDS
WHERE PROBABILITY_HACKER > 0.50;

SELECT NAME, RISK_LEVEL
FROM FRIENDS
WHERE RISK_LEVEL NOT LIKE 'SAFE';
