CREATE TABLE IF NOT EXISTS RESTAURANTS (
  NAME TEXT,
  CUISINE TEXT,
  NEIGHBOURHOOD TEXT,
  REVIEW TEXT,
  PRICE REAL,
  HEALTH TEXT
);

INSERT INTO RESTAURANTS (NAME, CUISINE, NEIGHBOURHOOD, REVIEW, PRICE, HEALTH) VALUES
('PETER', 'CHINESE', 'BROOKLYN', 'AWESOME', 234, 'A'),
('MARIO', 'ITALIAN', 'MANHATTAN', 'EXCELLENT', 310, 'A'),
('SUSHI ZEN', 'JAPANESE', 'QUEENS', 'GOOD', 190, 'B'),
('TACO LAND', 'MEXICAN', 'BRONX', 'AVERAGE', 120, 'B'),
('SPICE HUB', 'INDIAN', 'BROOKLYN', 'OUTSTANDING', 275, 'A'),
('BURGER BAY', 'AMERICAN', 'MANHATTAN', 'OKAY', 150, 'C'),
('GREEK DELIGHT', 'GREEK', 'QUEENS', 'EXCELLENT', 220, 'A'),
('PASTA PARADISO', 'ITALIAN', 'STATEN ISLAND', 'GOOD', 200, 'B'),
('VEGAN VIBES', 'VEGAN', 'BROOKLYN', 'LOVELY PLACE', 180, 'A'),
('DIM SUM HOUSE', 'CHINESE', 'MANHATTAN', 'FANTASTIC', 260, 'A');

SELECT * FROM RESTAURANTS;

SELECT DISTINCT NEIGHBOURHOOD FROM RESTAURANTS;

SELECT DISTINCT CUISINE FROM RESTAURANTS;

SELECT DISTINCT REVIEW FROM RESTAURANTS;

SELECT DISTINCT PRICE FROM RESTAURANTS;

SELECT * FROM RESTAURANTS WHERE CUISINE='CHINESE';

SELECT * FROM RESTAURANTS WHERE NEIGHBOURHOOD='QUEENS';

SELECT * FROM RESTAURANTS WHERE NAME LIKE '%DIM SUM HOUSE%';

SELECT * FROM RESTAURANTS WHERE PRICE<=150;

SELECT * FROM RESTAURANTS ORDER BY PRICE DESC;

SELECT * FROM RESTAURANTS ORDER BY NAME;

SELECT * FROM RESTAURANTS WHERE HEALTH LIKE '%A%';

SELECT MAX(PRICE) FROM RESTAURANTS;

SELECT MIN(PRICE) FROM RESTAURANTS;

SELECT CUISINE, AVG(PRICE)
FROM RESTAURANTS
GROUP BY CUISINE
HAVING AVG(PRICE) > 200;

SELECT * FROM RESTAURANTS WHERE HEALTH NOT IN ('C');

SELECT COUNT(*) FROM RESTAURANTS;

SELECT COUNT(DISTINCT CUISINE) FROM RESTAURANTS;