CREATE TABLE IF NOT EXISTS NOBEL_WIN(
  YEAR INTEGER, 
  SUBJECT TEXT,
  WINNER TEXT, 
  COUNTRY TEXT, 
  CATEGORY TEXT
);

INSERT INTO NOBEL_WIN(YEAR,SUBJECT,WINNER,COUNTRY,CATEGORY) VALUES
(1970,'PHYSICS','HANNAH','ENGLAND','GERMANIST'),
(1979,'PHYSICS','NIYA','INDIA','ECONOMIST'),
(1990,'HISTORY','PETER','AMERICA','HISTORIAN'),
(1998,'PSYCHOLOGY','ANNA','CHINA','PSYCHOLOGIST'),
(1978,'MATH','BECCA','ENGLAND','MATHEMATICIAN'),
(1987,'CHEMISTRY','REB','FINLAND','GERMANIST'),
(1970,'ENGLISH','STEVE','RUSSIA','LITERATURE'),
(1970,'MATH','WES','ESTONIA','GERMANIST');

SELECT YEAR, SUBJECT, WINNER, COUNTRY, CATEGORY 
FROM NOBEL_WIN;

SELECT * 
FROM NOBEL_WIN
WHERE SUBJECT NOT LIKE 'P%';

SELECT * 
FROM NOBEL_WIN
WHERE CATEGORY NOT LIKE 'H%';

