CREATE TABLE IF NOT EXISTS STUDENT(
ROLL_NO TEXT PRIMARY KEY ,
NAME TEXT NOT NULL ,
ADDRESS TEXT,
PHONE TEXT,
AGE INTEGER 

);

INSERT INTO STUDENT (ROLL_NO,NAME,ADDRESS,PHONE,AGE) VALUES
('1','RAM','DELHI','****','18'),
('2','RAMESH','ODISHA','****','16'),
('3','SURESH','BIHAR','****','17'),
('4','RINA','DELHI','****','19'),
('5','DEV','UP','****','20');

SELECT * FROM STUDENT;
SELECT * FROM STUDENT WHERE AGE='18' AND ADDRESS='DELHI';

SELECT * FROM STUDENT WHERE AGE='17' AND ADDRESS='BIHAR';

SELECT * FROM STUDENT WHERE AGE='18' OR AGE='20' AND ADDRESS='DELHI';

SELECT * FROM STUDENT WHERE  ADDRESS='UP';



