CREATE TABLE SUPPLIER
(
SNO TEXT PRIMARY KEY,
SNAME TEXT, 
STATUS INTEGER,
CITY TEXT

);

INSERT INTO SUPPLIER
(SNO,SNAME,STATUS,CITY)
VALUES

('S1','JOHN','20','LONDON'),
('S2','LIYA','10','DELHI'),
('S3','NICK','25','LONDON'),
('S4','JAS','21','PARIS'),
('S5','NINA','40','LONDON'); 
SELECT*
 FROM supplier;



